<nav id="navbar">
    <li><a href="home.php">Avalehele</a></li>
    <li><a href="userreg.php">Kasutajat tegema</a></li>
    <li><a href="motetesisestamine.php">Mõtteid sisestama</a></li>
    <li><a href="motetelist.php">Mõtteid vaatama</a></li>
    <li><a href="listfilms.php">Filmide list</a></li>
    <li><a href="addfilms.php">Filmide lisamine</a></li>
    <li><a href="userprofile.php">Minu kasutajaprofiil</a></li>
    <li><a href="filmandgenre.php">Filmide seoseid tegema</a></li>
    <li><a href="listfilmpersons.php">Filmide tegelased</a></li>
    <li><a href="photoupload_baas.php">Galeriipiltide üleslaadimine(baas)</a></li>
    <li><a href="photoupload.php">Galeriipiltide üleslaadimine</a></li><li>
    <li><a href="photogallery_public.php">Avalike piltide galerii</a></li>
    <li><a href="photogallery_private.php">Privaatsete piltide galerii</a></li>
    <li><a href="addnews.php">Uudiste lisamine</a></li>
    <li><a href="listnews.php">Uudiste muutmine ja kustutamine</a></li>
    <li><a href="viljavedu.php">Viljavedu</a></li>
    <li><a href="listviljavedu.php">Viljaveo andmed</a></li>
</nav> 